# Generated by Django 5.0.2 on 2026-04-17 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('camera_id', models.CharField(blank=True, help_text='ID камеры для данного места', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Парковочное место',
                'verbose_name_plural': 'Парковочные места',
                'ordering': ['zone', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('zone_type', models.CharField(choices=[('entrance', 'у входа'), ('far', 'дальние места'), ('disabled', 'инвалидные места'), ('vip', 'VIP'), ('cargo', 'грузовые')], default='entrance', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=10)),
                ('priority', models.IntegerField(default=0, help_text='Приоритет для рекомендации.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('is_guest', models.BooleanField(default=False, help_text='Гостевое бронирование')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='pending', max_length=20)),
                ('booking_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('camera_recording', models.BooleanField(default=False, help_text='Идет запись с какмер')),
                ('camera_recording_started', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingslot')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь (null для гостей)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_started', models.DateTimeField()),
                ('recording_ended', models.DateTimeField(blank=True, null=True)),
                ('video_path', models.CharField(blank=True, help_text='Путь к файлу записи', max_length=500)),
                ('snapshot_path', models.CharField(blank=True, help_text='Путь к скриншоту', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_logs', to='parking.parkingslot')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.reservation')),
            ],
            options={
                'verbose_name': 'Лог камеры',
                'verbose_name_plural': 'Логи камер',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TheftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('resolved', 'Решено'), ('false_alarm', 'Ложная тревога')], default='new', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('police_report_number', models.CharField(blank=True, max_length=50)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theft_reports', to='parking.reservation')),
            ],
            options={
                'verbose_name': 'Заявление об угоне',
                'verbose_name_plural': 'Заявления об угоне',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.zone'),
        ),
        migrations.CreateModel(
            name='OccupancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('occupied_count', models.IntegerField()),
                ('total_capacity', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('day_of_week', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_history', to='parking.zone')),
            ],
            options={
                'verbose_name': 'История загруженности',
                'verbose_name_plural': 'История загруженности',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['slot', 'status'], name='parking_res_slot_id_b44425_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time', 'end_time'], name='parking_res_start_t_a2bcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='parking_res_user_id_879c77_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['booking_code'], name='parking_res_booking_1f0e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['is_active', 'is_occupied'], name='parking_par_is_acti_45c17d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('zone', 'number')},
        ),
        migrations.AddIndex(
            model_name='occupancyhistory',
            index=models.Index(fields=['zone', 'timestamp'], name='parking_occ_zone_id_92671e_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancyhistory',
            index=models.Index(fields=['day_of_week', 'hour'], name='parking_occ_day_of__48741a_idx'),
        ),
    ]
