# Generated by Django 5.0.2 on 2026-04-25 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='parking_res_slot_id_b44425_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='parking_res_start_t_a2bcbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='parking_res_user_id_879c77_idx',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='camera_recording_started',
            new_name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='cameralog',
            name='snapshot_path',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='theftreport',
            name='police_report_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='theftreport',
            name='notes',
            field=models.TextField(blank=True, help_text='Заметки сотрудника'),
        ),
        migrations.AddField(
            model_name='theftreport',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cameralog',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_logs', to='parking.reservation'),
        ),
        migrations.AlterField(
            model_name='cameralog',
            name='video_path',
            field=models.CharField(blank=True, help_text='Путь к видеофайлу', max_length=255),
        ),
        migrations.AlterField(
            model_name='occupancyhistory',
            name='day_of_week',
            field=models.IntegerField(help_text='0=Понедельник, 6=Воскресенье'),
        ),
        migrations.AlterField(
            model_name='occupancyhistory',
            name='hour',
            field=models.IntegerField(help_text='0-23'),
        ),
        migrations.AlterField(
            model_name='occupancyhistory',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='occupancyhistory',
            name='occupied_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancyhistory',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='camera_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theftreport',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('resolved', 'Решено'), ('false_alarm', 'Ложная тревога')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'start_time'], name='parking_res_status_3c7802_idx'),
        ),
    ]
