# Generated by Django 5.0.2 on 2026-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_reservation_parking_res_slot_id_b44425_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
