# Generated by Django 5.0.2 on 2026-05-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_zone_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameralog',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='cameralog',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='occupancyhistory',
            name='zone',
        ),
        migrations.AlterModelOptions(
            name='parkingslot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='theftreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='parkingslot',
            name='parking_par_is_acti_45c17d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='parking_res_booking_1f0e1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='parking_res_status_3c7802_idx',
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='theftreport',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='theftreport',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='description',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='theftreport',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.reservation'),
        ),
        migrations.AlterField(
            model_name='theftreport',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('entrance', 'У входа'), ('far', 'Дальние места'), ('disabled', 'Инвалидные места'), ('vip', 'VIP'), ('cargo', 'Грузовые')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CameraLog',
        ),
        migrations.DeleteModel(
            name='OccupancyHistory',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='camera_id',
        ),
    ]
