# Generated by Django 5.0.2 on 2026-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_cameralog_reservation_remove_cameralog_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
