# Generated by Django 5.0.2 on 2026-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_reservation_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='license_plate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Государственный номер'),
        ),
    ]
