# Generated by Django 5.0.2 on 2026-05-15 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_reservation_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название камеры')),
                ('rtsp_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='RTSP URL камеры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_recording', models.BooleanField(default=False, verbose_name='Идёт запись')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Расположение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='parking.parkingslot', verbose_name='Парковочное место')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='CameraRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=500, verbose_name='Путь к видеофайлу')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к превью')),
                ('detected_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Распознанный номер')),
                ('expected_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ожидаемый номер (из брони)')),
                ('plate_matched', models.BooleanField(default=False, verbose_name='Номер совпал')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Точность распознавания (%)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Длительность (сек)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время обработки')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='parking.camera', verbose_name='Камера')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_recordings', to='parking.reservation', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Запись с камеры',
                'verbose_name_plural': 'Записи с камер',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
